(async function(){
  const page=document.body.dataset.page;
  try{
    const ctx=await dq.requireAuth(); if(!ctx)return;
    const role=dq.roleOf(ctx);
    if(!dq.allowed(ctx,page)){location.replace(role==='kitchen'?'orders.html':'dashboard.html');return}
    dq.shell(page,ctx);
    const rid=ctx.restaurant?.id;
    const content=document.getElementById('content');
    const q=async promise=>{const {data,error}=await promise;if(error)throw error;return data||[]};
    const head=(title,copy,button='')=>`<div class="section-head"><div><h1>${dq.esc(title)}</h1><p>${dq.esc(copy)}</p></div>${button}</div>`;
    const invitationUrl=token=>{const url=new URL('signup.html',location.href);url.searchParams.set('invite',token);return url.href};
    const showInvitation=(token,name='New user')=>{const url=invitationUrl(token);dq.modal('Invitation link',`<p>Copy this private link and send it to <strong>${dq.esc(name)}</strong>. They will use it to create their password and join the system.</p><div class="code-link">${dq.esc(url)}</div><button class="btn" id="copy-invitation" style="margin-top:1rem">Copy invitation link</button>`);document.getElementById('copy-invitation').onclick=async()=>{await navigator.clipboard.writeText(url);dq.toast('Invitation link copied.')}};

    async function dashboard(){
      if(role==='super_admin'){
        const [restaurants,invites]=await Promise.all([q(dq.db.from('restaurants').select('*').order('created_at',{ascending:false})),q(dq.db.from('staff_invitations').select('*').order('created_at',{ascending:false}))]);
        content.innerHTML=head('Platform overview','Create and oversee restaurant companies.','<a class="btn" href="companies.html">Add company</a>')+`<div class="metrics"><div class="metric"><small>Companies</small><strong>${restaurants.length}</strong></div><div class="metric"><small>Active companies</small><strong>${restaurants.filter(x=>x.active).length}</strong></div><div class="metric"><small>Pending owners</small><strong>${invites.filter(x=>!x.accepted_at&&x.role==='owner').length}</strong></div><div class="metric"><small>Currency</small><strong>USD</strong></div></div><div class="card"><h2>Newest companies</h2><div class="list">${restaurants.slice(0,8).map(r=>`<div class="list-row"><div><strong>${dq.esc(r.name)}</strong><p>${dq.date(r.created_at)}</p></div><span class="badge ${r.active?'active':'inactive'}">${r.active?'Active':'Inactive'}</span></div>`).join('')||'<div class="empty">No companies yet.</div>'}</div></div>`;return;
      }
      const [tables,sessions,orders,requests]=await Promise.all([q(dq.db.from('physical_tables').select('*').eq('restaurant_id',rid).eq('active',true)),q(dq.db.from('table_sessions').select('*').eq('restaurant_id',rid).neq('status','closed')),q(dq.db.from('orders').select('*').eq('restaurant_id',rid).gte('created_at',new Date(new Date().setHours(0,0,0,0)).toISOString()).order('created_at',{ascending:false})),q(dq.db.from('customer_requests').select('*').eq('restaurant_id',rid).neq('status','resolved').order('created_at',{ascending:false}))]);
      content.innerHTML=head(`Good ${new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}`,`Here is what is happening at ${ctx.restaurant.name}.`)+`<div class="metrics"><div class="metric"><small>Open tables</small><strong>${sessions.length}/${tables.length}</strong></div><div class="metric"><small>Pending orders</small><strong>${orders.filter(x=>x.status==='pending').length}</strong></div><div class="metric"><small>Orders today</small><strong>${orders.length}</strong></div><div class="metric"><small>Guest requests</small><strong>${requests.length}</strong></div></div><div class="grid-2"><div class="card"><h2>Latest orders</h2><div class="list">${orders.slice(0,6).map(o=>`<div class="list-row"><div><strong>Order #${o.order_number}</strong><p>${dq.date(o.created_at)}</p></div><span class="badge ${o.status}">${o.status}</span></div>`).join('')||'<div class="empty">No orders today.</div>'}</div></div><div class="card"><h2>Guest requests</h2><div class="list">${requests.slice(0,6).map(r=>`<div class="list-row"><div><strong>${r.type==='bill'?'Bill requested':'Waiter requested'}</strong><p>${dq.date(r.created_at)}</p></div><button class="btn small resolve-request" data-id="${r.id}">Resolve</button></div>`).join('')||'<div class="empty">No open requests.</div>'}</div></div></div>`;
      document.querySelectorAll('.resolve-request').forEach(b=>b.onclick=async()=>{try{const {error}=await dq.db.from('customer_requests').update({status:'resolved',resolved_by:ctx.profile.id,resolved_at:new Date().toISOString()}).eq('id',b.dataset.id);if(error)throw error;dashboard();dq.toast('Request resolved.')}catch(x){dq.err(x)}});
    }

    async function companies(){
      const [rows,invites,payments]=await Promise.all([q(dq.db.from('restaurants').select('*').order('created_at',{ascending:false})),q(dq.db.from('staff_invitations').select('*').eq('role','owner').order('created_at',{ascending:false})),q(dq.db.from('owner_payments').select('*').order('payment_date',{ascending:false}))]);
      content.innerHTML=head('Restaurant companies','Add companies, invite owners, and control company access.','<button class="btn" id="add-company">Add company</button>')+`<div class="card table-wrap"><table class="data-table"><thead><tr><th>Company</th><th>Owner</th><th>Phone</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.map(r=>{const i=invites.find(x=>x.restaurant_id===r.id),paymentCount=payments.filter(x=>x.restaurant_id===r.id).length;return `<tr><td><strong>${dq.esc(r.name)}</strong><br><span class="muted">${dq.esc(r.slug)}</span></td><td>${dq.esc(i?.full_name||'—')}<br><span class="muted">${dq.esc(i?.email||'—')}</span></td><td>${dq.esc(i?.phone||'—')}</td><td><span class="badge ${r.active?'active':'inactive'}">${r.active?'Active':'Suspended'}</span></td><td><div class="actions"><button class="btn ghost small view-company-payments" data-id="${r.id}">Payments (${paymentCount})</button><button class="btn ghost small edit-company" data-id="${r.id}">Edit</button><button class="btn secondary small suspend-company" data-id="${r.id}" data-active="${r.active}">${r.active?'Suspend':'Activate'}</button>${i&&!i.accepted_at?`<button class="btn ghost small copy-owner-invite" data-token="${i.invite_token}" data-name="${dq.esc(i.full_name)}">Invite link</button>`:''}<button class="btn danger small delete-company" data-id="${r.id}" data-name="${dq.esc(r.name)}">Delete</button></div></td></tr>`}).join('')}</tbody></table>${rows.length?'':'<div class="empty">No companies yet.</div>'}</div>`;
      document.getElementById('add-company').onclick=()=>{dq.modal('Add restaurant company',`<form id="company-form"><label>Company name<input class="input" name="company_name" required></label><label>Owner full name<input class="input" name="owner_name" required></label><label>Owner email<input class="input" type="email" name="owner_email" required></label><label>Owner phone number<input class="input" type="tel" name="owner_phone" required></label><p class="muted">After creating the company, DineQR will give you a private signup link to send to the owner.</p><button class="btn" type="submit">Create company</button></form>`);document.getElementById('company-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');dq.setBusy(b,true);try{const x=dq.formData(e.target),{data,error}=await dq.db.rpc('create_restaurant_company',x);if(error)throw error;await companies();showInvitation(data.invite_token,x.owner_name)}catch(x){dq.err(x)}finally{dq.setBusy(b,false)}}};
      document.querySelectorAll('.copy-owner-invite').forEach(b=>b.onclick=()=>showInvitation(b.dataset.token,b.dataset.name));
      document.querySelectorAll('.view-company-payments').forEach(b=>b.onclick=()=>{const r=rows.find(x=>x.id===b.dataset.id),history=payments.filter(x=>x.restaurant_id===r.id),total=history.reduce((sum,p)=>sum+Number(p.amount),0);dq.modal(`${r.name} payments`,`<div class="metric" style="margin-bottom:1rem"><small>Total recorded</small><strong>${dq.money(total)}</strong></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Amount</th><th>Method</th><th>Notes</th></tr></thead><tbody>${history.map(p=>`<tr><td>${dq.esc(p.payment_date)}</td><td><strong>${dq.money(p.amount)}</strong></td><td>${dq.esc(String(p.method).replace('_',' '))}</td><td>${dq.esc(p.notes||'—')}</td></tr>`).join('')}</tbody></table>${history.length?'':'<div class="empty">No payments recorded for this owner.</div>'}</div><a class="btn" href="admin-finance.html" style="margin-top:1rem">Open owner payments</a>`)});
      document.querySelectorAll('.suspend-company').forEach(b=>b.onclick=async()=>{try{const active=b.dataset.active!=='true',{error}=await dq.db.rpc('admin_set_restaurant_status',{target_restaurant:b.dataset.id,new_active:active});if(error)throw error;dq.toast(active?'Company activated.':'Company suspended.');companies()}catch(x){dq.err(x)}});
      document.querySelectorAll('.delete-company').forEach(b=>b.onclick=async()=>{if(!confirm(`Delete ${b.dataset.name}? This permanently deletes its tables, menu, orders, staff links, receipts and payments.`))return;try{const {error}=await dq.db.from('restaurants').delete().eq('id',b.dataset.id);if(error)throw error;dq.toast('Company deleted.');companies()}catch(x){dq.err(x)}});
      document.querySelectorAll('.edit-company').forEach(b=>b.onclick=()=>{const r=rows.find(x=>x.id===b.dataset.id),i=invites.find(x=>x.restaurant_id===r.id);dq.modal('Edit company',`<form id="edit-company-form"><label>Company name<input class="input" name="name" value="${dq.esc(r.name)}" required></label><label>Owner phone number<input class="input" name="phone" value="${dq.esc(i?.phone||'')}"></label><button class="btn">Save changes</button></form>`);document.getElementById('edit-company-form').onsubmit=async e=>{e.preventDefault();const x=dq.formData(e.target);try{const {error}=await dq.db.from('restaurants').update({name:x.name.trim()}).eq('id',r.id);if(error)throw error;if(i){const {error:inviteError}=await dq.db.from('staff_invitations').update({phone:x.phone.trim()||null}).eq('id',i.id);if(inviteError)throw inviteError}dq.closeModal();dq.toast('Company updated.');companies()}catch(x){dq.err(x)}}});
    }

    async function tables(){
      const [tableRows,sessions]=await Promise.all([q(dq.db.from('physical_tables').select('*').eq('restaurant_id',rid).eq('active',true).order('label')),q(dq.db.from('table_sessions').select('*').eq('restaurant_id',rid).neq('status','closed'))]);const byTable=Object.fromEntries(sessions.map(s=>[s.table_id,s]));const canAdd=['owner','manager'].includes(role),canOpen=['owner','manager','waiter'].includes(role),canClose=['owner','manager','waiter','cashier'].includes(role);
      content.innerHTML=head('Dining room','Open a table to create a new one-time QR code.',canAdd?'<button class="btn" id="add-table">Add table</button>':'')+`<div class="table-grid">${tableRows.map(t=>{const s=byTable[t.id];return `<div class="table-card"><div class="status"><span class="badge ${s?s.status:'closed'}">${s?s.status.replace('_',' '):'Available'}</span><span class="muted">${t.seats} seats</span></div><h3>${dq.esc(t.label)}</h3><p class="muted">${s?'Opened '+dq.date(s.opened_at):'Ready for the next guests'}</p><div class="actions">${!s&&canOpen?`<button class="btn small open-table" data-id="${t.id}">Open table</button>`:''}${s?`<button class="btn secondary small show-qr" data-id="${s.id}">View QR</button><button class="btn ghost small view-table-orders" data-id="${s.id}" data-label="${dq.esc(t.label)}">View orders</button>`:''}${s&&canClose?`<button class="btn ghost small close-table" data-id="${s.id}" data-label="${dq.esc(t.label)}">Close & receipt</button>`:''}${canAdd?`<button class="btn ghost small edit-table" data-id="${t.id}">Edit</button>`:''}${canAdd&&!s?`<button class="btn danger small delete-table" data-id="${t.id}" data-label="${dq.esc(t.label)}">Delete</button>`:''}</div></div>`}).join('')||'<div class="empty">No tables have been added.</div>'}</div>`;
      document.getElementById('add-table')?.addEventListener('click',()=>{dq.modal('Add a table',`<form id="table-form"><label>Table name or number<input class="input" name="label" placeholder="Table 1" required></label><label>Number of seats<input class="input" name="seats" type="number" min="1" max="100" value="2" required></label><button class="btn" type="submit">Add table</button></form>`);document.getElementById('table-form').onsubmit=async e=>{e.preventDefault();const x=dq.formData(e.target);try{const {error}=await dq.db.from('physical_tables').insert({restaurant_id:rid,label:x.label.trim(),seats:Number(x.seats)});if(error)throw error;dq.closeModal();tables();dq.toast('Table added.')}catch(x){dq.err(x)}}});
      document.querySelectorAll('.open-table').forEach(b=>b.onclick=async()=>{dq.setBusy(b,true,'Opening…');try{const {data,error}=await dq.db.rpc('open_table_session',{target_table:b.dataset.id});if(error)throw error;dq.toast('Table opened. New QR code created.');await tables();showQr(data.public_token,data.table_label)}catch(x){dq.err(x)}finally{dq.setBusy(b,false)}});
      document.querySelectorAll('.show-qr').forEach(b=>b.onclick=()=>{const s=sessions.find(x=>x.id===b.dataset.id),t=tableRows.find(x=>x.id===s.table_id);showQr(s.public_token,t.label)});
      document.querySelectorAll('.view-table-orders').forEach(b=>b.onclick=()=>viewTableOrders(b.dataset.id,b.dataset.label));
      document.querySelectorAll('.close-table').forEach(b=>b.onclick=()=>closeTable(b.dataset.id,b.dataset.label));
      document.querySelectorAll('.edit-table').forEach(b=>b.onclick=()=>{const t=tableRows.find(x=>x.id===b.dataset.id);dq.modal(`Edit ${t.label}`,`<form id="edit-table-form"><label>Table name or number<input class="input" name="label" value="${dq.esc(t.label)}" required></label><label>Number of seats<input class="input" name="seats" type="number" min="1" max="100" value="${t.seats}" required></label><button class="btn">Save table</button></form>`);document.getElementById('edit-table-form').onsubmit=async e=>{e.preventDefault();const x=dq.formData(e.target);try{const {error}=await dq.db.from('physical_tables').update({label:x.label.trim(),seats:Number(x.seats)}).eq('id',t.id);if(error)throw error;dq.closeModal();dq.toast('Table updated.');tables()}catch(error){dq.err(error)}}});
      document.querySelectorAll('.delete-table').forEach(b=>b.onclick=async()=>{if(!confirm(`Delete ${b.dataset.label}? Its previous order and receipt history will be kept.`))return;try{const {error}=await dq.db.from('physical_tables').update({active:false}).eq('id',b.dataset.id);if(error)throw error;dq.toast('Table deleted.');tables()}catch(error){dq.err(error)}});
    }
    async function viewTableOrders(sessionId,label){try{const orderRows=await q(dq.db.from('orders').select('*').eq('session_id',sessionId).order('created_at',{ascending:false})),orderIds=orderRows.map(o=>o.id),items=orderIds.length?await q(dq.db.from('order_items').select('*').in('order_id',orderIds)):[];dq.modal(`${label} current orders`,`<div class="list">${orderRows.map(o=>`<div class="card" style="box-shadow:none"><div class="list-row" style="border:0;padding:0 0 .6rem"><div><strong>Order #${o.order_number}</strong><p>${dq.date(o.created_at)}</p></div><span class="badge ${o.status}">${o.status}</span></div>${items.filter(i=>i.order_id===o.id).map(i=>`<div class="order-item ${i.voided_at?'void':''}"><span>${i.quantity} × ${dq.esc(i.item_name_snapshot)}</span><span>${dq.money(Number(i.unit_price_snapshot)*i.quantity)}</span></div>`).join('')}</div>`).join('')||'<div class="empty">This table has not placed an order yet.</div>'}</div>`)}catch(error){dq.err(error)}}
    function showQr(token,label){const url=new URL('customer.html',location.href);url.searchParams.set('token',token);dq.modal(`QR code · ${label}`,`<div class="qr-box"><div id="qr"></div></div><p class="code-link">${dq.esc(url.href)}</p><div class="actions no-print"><button class="btn" id="print-qr">Print QR code</button><button class="btn secondary" id="copy-link">Copy link</button></div>`);if(window.QRCode)new QRCode(document.getElementById('qr'),{text:url.href,width:280,height:280,correctLevel:QRCode.CorrectLevel.M});else dq.err(new Error('QR code library did not load'));document.getElementById('print-qr').onclick=()=>window.print();document.getElementById('copy-link').onclick=async()=>{await navigator.clipboard.writeText(url.href);dq.toast('Customer link copied.')}}
    async function closeTable(id,label){try{const discounts=await q(dq.db.from('discounts').select('*').eq('restaurant_id',rid).eq('active',true));dq.modal(`Close ${label}`,`<form id="close-form"><p>Record the one final offline payment and close this table session. The QR code will stop working immediately.</p><label>Discount<select name="discount"><option value="">No discount</option>${discounts.map(d=>`<option value="${d.id}">${dq.esc(d.name)} · ${d.kind==='percentage'?d.value+'%':dq.money(d.value)}</option>`).join('')}</select></label><label>Payment method<select name="method"><option value="cash">Cash</option><option value="card">Card</option><option value="bank_transfer">Bank transfer</option><option value="other">Other</option></select></label><button class="btn danger" type="submit">Record payment & close</button></form>`);document.getElementById('close-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');dq.setBusy(b,true,'Closing…');try{const {method,discount}=dq.formData(e.target);if(discount){const {error:discountError}=await dq.db.rpc('apply_discount_to_session',{target_session:id,target_discount:discount});if(discountError)throw discountError}const {data,error}=await dq.db.rpc('close_table_session',{target_session:id,method});if(error)throw error;showReceipt(data,label);tables()}catch(x){dq.err(x)}finally{dq.setBusy(b,false)}}}catch(x){dq.err(x)}}
    function showReceipt(r,label){dq.modal('Final receipt',`<div class="receipt"><div style="text-align:center"><h2>${dq.esc(ctx.restaurant.name)}</h2><p>${dq.esc(label)} · ${dq.date(new Date())}</p></div>${(r.items||[]).map(i=>`<div class="line"><span>${i.quantity} × ${dq.esc(i.name)}</span><span>${dq.money(Number(i.unit_price)*i.quantity)}</span></div>`).join('')}<div class="line" style="border-top:1px dashed #777;margin-top:.5rem;padding-top:.6rem"><span>Subtotal</span><span>${dq.money(r.subtotal)}</span></div><div class="line"><span>Discount</span><span>−${dq.money(r.discount)}</span></div><div class="line"><span>Tax</span><span>${r.tax_configured?dq.money(r.tax):'—'}</span></div><div class="line"><span>Service charge</span><span>${r.service_configured?dq.money(r.service_charge):'—'}</span></div><div class="line total"><span>Total</span><span>${dq.money(r.total)}</span></div><div class="line"><span>Payment</span><span>${dq.esc(r.payment_method.replace('_',' '))}</span></div></div><button class="btn no-print" style="margin-top:1rem" onclick="window.print()">Print receipt</button>`)}

    async function orders(){
      const [orderRows,items,sessions,tableRows]=await Promise.all([q(dq.db.from('orders').select('*').eq('restaurant_id',rid).neq('status','served').neq('status','rejected').order('created_at',{ascending:false})),q(dq.db.from('order_items').select('*')),q(dq.db.from('table_sessions').select('id,table_id').eq('restaurant_id',rid)),q(dq.db.from('physical_tables').select('id,label').eq('restaurant_id',rid))]);const tableMap=Object.fromEntries(tableRows.map(x=>[x.id,x.label])),sessionMap=Object.fromEntries(sessions.map(x=>[x.id,tableMap[x.table_id]]));
      content.innerHTML=head(role==='kitchen'?'Kitchen orders':'Live orders','New customer orders must be accepted before the kitchen prepares them.')+`<div class="order-grid">${orderRows.map(o=>{const its=items.filter(i=>i.order_id===o.id);return `<article class="order-card"><div class="order-head"><div><strong>${dq.esc(sessionMap[o.session_id]||'Table')}</strong><div class="muted">Order #${o.order_number} · ${dq.date(o.created_at)}</div></div><span class="badge ${o.status}">${o.status}</span></div><div class="order-body">${its.map(i=>`<div class="order-item ${i.voided_at?'void':''}"><span>${i.quantity} × ${dq.esc(i.item_name_snapshot)}${i.special_instructions?`<small class="muted"><br>${dq.esc(i.special_instructions)}</small>`:''}</span><span>${dq.money(i.unit_price_snapshot*i.quantity)}</span></div>`).join('')}</div><div class="order-actions">${nextButtons(o,its)}</div></article>`}).join('')||'<div class="empty">No active orders.</div>'}</div>`;
      document.querySelectorAll('[data-next]').forEach(b=>b.onclick=async()=>{let reason=null;if(b.dataset.next==='rejected'){reason=prompt('Reason for rejecting this order:');if(!reason)return}dq.setBusy(b,true);try{const {error}=await dq.db.rpc('set_order_status',{target_order:b.dataset.id,next_status:b.dataset.next,reason});if(error)throw error;orders()}catch(x){dq.err(x)}finally{dq.setBusy(b,false)}});
      document.querySelectorAll('[data-void]').forEach(b=>b.onclick=async()=>{const reason=prompt('Required reason for voiding this item:');if(!reason)return;try{const {error}=await dq.db.rpc('void_order_item',{target_item:b.dataset.void,reason});if(error)throw error;orders()}catch(x){dq.err(x)}});
    }
    function nextButtons(o,its){let out='';if(o.status==='pending')out=`<button class="btn small" data-next="accepted" data-id="${o.id}">Accept</button><button class="btn danger small" data-next="rejected" data-id="${o.id}">Reject</button>`;if(o.status==='accepted')out=`<button class="btn small" data-next="preparing" data-id="${o.id}">Start preparing</button>`;if(o.status==='preparing')out=`<button class="btn small" data-next="ready" data-id="${o.id}">Mark ready</button>`;if(o.status==='ready')out=`<button class="btn small" data-next="served" data-id="${o.id}">Mark served</button>`;if(['owner','manager','waiter'].includes(role)&&o.status!=='pending')out+=its.filter(i=>!i.voided_at).map(i=>`<button class="btn ghost small" data-void="${i.id}">Void ${dq.esc(i.item_name_snapshot)}</button>`).join('');return out}

    async function menu(){
      const [cats,items]=await Promise.all([q(dq.db.from('menu_categories').select('*').eq('restaurant_id',rid).order('sort_order')),q(dq.db.from('menu_items').select('*').eq('restaurant_id',rid).order('sort_order'))]);
      content.innerHTML=head('Menu','Organize categories and add pictures to the items guests can order.','<button class="btn" id="add-item">Add menu item</button>')+`<div class="menu-admin-grid"><aside class="card"><div class="section-head" style="align-items:center"><div><h2>Categories</h2><p>${cats.length} categories</p></div><button class="btn secondary small" id="add-category">Add</button></div><div class="category-list"><div class="list-row"><strong>Uncategorized</strong><span class="badge">${items.filter(i=>!i.category_id).length}</span></div>${cats.map(c=>`<div class="list-row"><strong>${dq.esc(c.name)}</strong><span class="badge">${items.filter(i=>i.category_id===c.id).length}</span></div>`).join('')}</div></aside><section class="card table-wrap"><h2>Menu items</h2><table class="data-table"><thead><tr><th>Picture</th><th>Item</th><th>Category</th><th>Price</th><th>Available</th><th></th></tr></thead><tbody>${items.map(i=>`<tr><td>${i.image_url?`<img class="menu-thumb" src="${dq.esc(i.image_url)}" alt="">`:'<div class="menu-thumb placeholder">No image</div>'}</td><td><strong>${dq.esc(i.name)}</strong><br><span class="muted">${dq.esc(i.description||'—')}</span></td><td>${dq.esc(cats.find(c=>c.id===i.category_id)?.name||'Uncategorized')}</td><td>${dq.money(i.price)}</td><td><span class="badge ${i.available?'active':'inactive'}">${i.available?'Yes':'No'}</span></td><td><button class="btn ghost small edit-item" data-id="${i.id}">Edit</button></td></tr>`).join('')}</tbody></table>${items.length?'':'<div class="empty">Add your first menu item.</div>'}</section></div>`;
      document.getElementById('add-category').onclick=()=>categoryModal();document.getElementById('add-item').onclick=()=>itemModal();document.querySelectorAll('.edit-item').forEach(b=>b.onclick=()=>itemModal(items.find(i=>i.id===b.dataset.id)));
      function categoryModal(){dq.modal('Add menu category',`<form id="cat-form"><label>Category name<input class="input" name="name" placeholder="Main courses" required></label><button class="btn">Add category</button></form>`);document.getElementById('cat-form').onsubmit=async e=>{e.preventDefault();try{const {name}=dq.formData(e.target),{error}=await dq.db.from('menu_categories').insert({restaurant_id:rid,name:name.trim()});if(error)throw error;dq.closeModal();menu()}catch(x){dq.err(x)}}}
      function itemModal(item){dq.modal(item?'Edit menu item':'Add menu item',`<form id="item-form"><label>Item name<input class="input" name="name" value="${dq.esc(item?.name||'')}" required></label><label>Description<textarea name="description" rows="3">${dq.esc(item?.description||'')}</textarea></label><div class="field-row"><label>Price (USD)<input class="input" type="number" step="0.01" min="0" name="price" value="${item?.price??''}" required></label><label>Category<select name="category_id"><option value="">Uncategorized</option>${cats.map(c=>`<option value="${c.id}" ${c.id===item?.category_id?'selected':''}>${dq.esc(c.name)}</option>`).join('')}</select></label></div><label>Item picture<input class="input" type="file" name="image" accept="image/jpeg,image/png,image/webp,image/gif"><small class="muted">JPG, PNG, WebP or GIF. Maximum 5 MB.${item?.image_url?' Leave empty to keep the current picture.':''}</small></label>${item?.image_url?`<img class="menu-preview" src="${dq.esc(item.image_url)}" alt="Current picture">`:''}<label><span><input type="checkbox" name="available" ${item?.available===false?'':'checked'}> Available to customers</span></label><button class="btn">${item?'Save changes':'Add item'}</button></form>`);document.getElementById('item-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button'),x=dq.formData(e.target),file=e.target.image.files[0],payload={restaurant_id:rid,name:x.name.trim(),description:x.description.trim(),price:Number(x.price),category_id:x.category_id||null,available:e.target.available.checked,image_url:item?.image_url||null};dq.setBusy(button,true,file?'Uploading picture…':'Saving…');try{if(file)payload.image_url=await uploadMenuImage(file);const {error}=item?await dq.db.from('menu_items').update(payload).eq('id',item.id):await dq.db.from('menu_items').insert(payload);if(error)throw error;dq.closeModal();menu();dq.toast(item?'Menu item updated.':'Menu item added.')}catch(error){dq.err(error)}finally{dq.setBusy(button,false)}}}
      async function uploadMenuImage(file){if(file.size>5242880)throw new Error('The picture must be smaller than 5 MB.');if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type))throw new Error('Please choose a JPG, PNG, WebP or GIF picture.');const extension=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase(),filePath=`${rid}/${crypto.randomUUID()}.${extension}`;const {error}=await dq.db.storage.from('menu-images').upload(filePath,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(error)throw error;return dq.db.storage.from('menu-images').getPublicUrl(filePath).data.publicUrl}
    }

    async function staff(){
      const [members,invites]=await Promise.all([q(dq.db.from('restaurant_members').select('*').eq('restaurant_id',rid).order('created_at')),q(dq.db.from('staff_invitations').select('*').eq('restaurant_id',rid).order('created_at',{ascending:false}))]);const profiles=members.length?await q(dq.db.from('profiles').select('*').in('id',members.map(m=>m.user_id))):[];
      content.innerHTML=head('Staff','Invite team members and control active access.','<button class="btn" id="invite">Invite staff</button>')+`<div class="grid-2"><div class="card"><h2>Active accounts</h2><div class="list">${members.map(m=>{const p=profiles.find(x=>x.id===m.user_id),canManage=m.role!=='owner'&&(role==='owner'||m.role!=='manager');return `<div class="list-row"><div><strong>${dq.esc(p?.full_name||p?.email||'Team member')}</strong><p>${dq.esc(m.role)}</p></div>${canManage?`<button class="btn ${m.active?'ghost':'secondary'} small toggle-member" data-id="${m.id}" data-active="${m.active}">${m.active?'Deactivate':'Activate'}</button>`:`<span class="badge ${m.active?'active':'inactive'}">${m.role}</span>`}</div>`}).join('')||'<div class="empty">No registered staff.</div>'}</div></div><div class="card"><h2>Invitations</h2><div class="list">${invites.map(i=>`<div class="list-row"><div><strong>${dq.esc(i.full_name)}</strong><p>${dq.esc(i.email)} · ${dq.esc(i.role)}</p></div>${i.accepted_at?'<span class="badge active">Joined</span>':`<button class="btn ghost small staff-invite-link" data-token="${i.invite_token}" data-name="${dq.esc(i.full_name)}">Copy link</button>`}</div>`).join('')||'<div class="empty">No invitations.</div>'}</div></div></div>`;
      document.getElementById('invite').onclick=()=>{dq.modal('Invite a staff member',`<form id="invite-form"><label>Full name<input class="input" name="staff_name" required></label><label>Email<input class="input" type="email" name="staff_email" required></label><label>Role<select name="staff_role"><option value="waiter">Waiter</option><option value="kitchen">Kitchen</option><option value="cashier">Cashier</option>${role==='owner'?'<option value="manager">Manager</option>':''}</select></label><p class="muted">DineQR will create a private signup link for this staff member.</p><button class="btn">Create invitation</button></form>`);document.getElementById('invite-form').onsubmit=async e=>{e.preventDefault();const x=dq.formData(e.target);try{const {data,error}=await dq.db.rpc('invite_staff',{target_restaurant:rid,...x});if(error)throw error;await staff();showInvitation(data.invite_token,x.staff_name)}catch(x){dq.err(x)}}};document.querySelectorAll('.staff-invite-link').forEach(b=>b.onclick=()=>showInvitation(b.dataset.token,b.dataset.name));document.querySelectorAll('.toggle-member').forEach(b=>b.onclick=async()=>{try{const {error}=await dq.db.from('restaurant_members').update({active:b.dataset.active!=='true'}).eq('id',b.dataset.id);if(error)throw error;staff()}catch(x){dq.err(x)}})
    }

    async function finance(){
      const receipts=await q(dq.db.from('receipts').select('*').eq('restaurant_id',rid).order('closed_at',{ascending:false}));const total=receipts.reduce((s,r)=>s+Number(r.total_snapshot||0),0),today=receipts.filter(r=>new Date(r.closed_at).toDateString()===new Date().toDateString()).reduce((s,r)=>s+Number(r.total_snapshot||0),0);let discounts=[];if(role==='owner')discounts=await q(dq.db.from('discounts').select('*').eq('restaurant_id',rid).order('created_at',{ascending:false}));
      content.innerHTML=head(role==='cashier'?'Receipts':'Finances','One final recorded payment for every closed table session.',role==='owner'?'<button class="btn" id="add-discount">Add discount</button>':'')+`<div class="metrics"><div class="metric"><small>Revenue today</small><strong>${dq.money(today)}</strong></div><div class="metric"><small>All recorded revenue</small><strong>${dq.money(total)}</strong></div><div class="metric"><small>Closed sessions</small><strong>${receipts.length}</strong></div><div class="metric"><small>Average bill</small><strong>${dq.money(receipts.length?total/receipts.length:0)}</strong></div></div>${role==='owner'?`<div class="card" style="margin-bottom:1rem"><h2>Available discounts</h2><div class="actions">${discounts.map(d=>`<span class="badge ${d.active?'active':'inactive'}">${dq.esc(d.name)} · ${d.kind==='percentage'?d.value+'%':dq.money(d.value)}</span>`).join('')||'<span class="muted">No discounts created.</span>'}</div></div>`:''}<div class="card table-wrap"><h2>Receipt history</h2><table class="data-table"><thead><tr><th>Table</th><th>Closed</th><th>Subtotal</th><th>Discount</th><th>Tax + service</th><th>Total</th><th>Payment</th></tr></thead><tbody>${receipts.map(r=>`<tr><td>${dq.esc(r.table_label)}</td><td>${dq.date(r.closed_at)}</td><td>${dq.money(r.subtotal_snapshot)}</td><td>${dq.money(r.discount_snapshot)}</td><td>${dq.money(Number(r.tax_snapshot)+Number(r.service_snapshot))}</td><td><strong>${dq.money(r.total_snapshot)}</strong></td><td>${dq.esc((r.payment_method||'—').replace('_',' '))}</td></tr>`).join('')}</tbody></table>${receipts.length?'':'<div class="empty">No closed table sessions yet.</div>'}</div>`;
      document.getElementById('add-discount')?.addEventListener('click',()=>{dq.modal('Add discount',`<form id="discount-form"><label>Name<input class="input" name="name" placeholder="Staff discount" required></label><div class="field-row"><label>Type<select name="kind"><option value="percentage">Percentage</option><option value="fixed">Fixed USD amount</option></select></label><label>Value<input class="input" type="number" min="0" step="0.01" name="value" required></label></div><button class="btn">Add discount</button></form>`);document.getElementById('discount-form').onsubmit=async e=>{e.preventDefault();const x=dq.formData(e.target);try{const {error}=await dq.db.from('discounts').insert({restaurant_id:rid,name:x.name.trim(),kind:x.kind,value:Number(x.value),created_by:ctx.profile.id});if(error)throw error;dq.closeModal();finance()}catch(x){dq.err(x)}}})
    }

    async function adminFinance(){
      const [payments,restaurants]=await Promise.all([q(dq.db.from('owner_payments').select('*').order('payment_date',{ascending:false}).order('created_at',{ascending:false})),q(dq.db.from('restaurants').select('id,name,active').order('name'))]);const names=Object.fromEntries(restaurants.map(r=>[r.id,r.name])),total=payments.reduce((s,p)=>s+Number(p.amount),0),monthKey=new Date().toISOString().slice(0,7),thisMonth=payments.filter(p=>String(p.payment_date).startsWith(monthKey)).reduce((s,p)=>s+Number(p.amount),0);
      content.innerHTML=head('Owner payments','Manually record payments restaurant owners make to DineQR. No online payment is processed.','<button class="btn" id="record-owner-payment">Record payment</button>')+`<div class="metrics"><div class="metric"><small>Total recorded</small><strong>${dq.money(total)}</strong></div><div class="metric"><small>This month</small><strong>${dq.money(thisMonth)}</strong></div><div class="metric"><small>Payments</small><strong>${payments.length}</strong></div><div class="metric"><small>Companies</small><strong>${restaurants.length}</strong></div></div><div class="card table-wrap"><table class="data-table"><thead><tr><th>Company</th><th>Date</th><th>Amount</th><th>Method</th><th>Notes</th><th></th></tr></thead><tbody>${payments.map(p=>`<tr><td><strong>${dq.esc(names[p.restaurant_id]||'Deleted company')}</strong></td><td>${dq.esc(p.payment_date)}</td><td><strong>${dq.money(p.amount)}</strong></td><td>${dq.esc(String(p.method).replace('_',' '))}</td><td>${dq.esc(p.notes||'—')}</td><td><button class="btn danger small delete-owner-payment" data-id="${p.id}">Delete</button></td></tr>`).join('')}</tbody></table>${payments.length?'':'<div class="empty">No owner payments recorded yet.</div>'}</div>`;
      document.getElementById('record-owner-payment').onclick=()=>{dq.modal('Record owner payment',`<form id="owner-payment-form"><label>Restaurant company<select name="restaurant_id" required><option value="">Select company</option>${restaurants.map(r=>`<option value="${r.id}">${dq.esc(r.name)}${r.active?'':' (suspended)'}</option>`).join('')}</select></label><div class="field-row"><label>Amount (USD)<input class="input" type="number" min="0.01" step="0.01" name="amount" required></label><label>Payment date<input class="input" type="date" name="payment_date" value="${new Date().toISOString().slice(0,10)}" required></label></div><label>Method<select name="method"><option value="cash">Cash</option><option value="card">Card</option><option value="bank_transfer">Bank transfer</option><option value="other">Other</option></select></label><label>Notes<textarea name="notes" rows="3" placeholder="Optional reference or details"></textarea></label><button class="btn">Save payment</button></form>`);document.getElementById('owner-payment-form').onsubmit=async e=>{e.preventDefault();const x=dq.formData(e.target);try{const {error}=await dq.db.from('owner_payments').insert({restaurant_id:x.restaurant_id,amount:Number(x.amount),payment_date:x.payment_date,method:x.method,notes:x.notes.trim()||null,recorded_by:ctx.profile.id});if(error)throw error;dq.closeModal();dq.toast('Owner payment recorded.');adminFinance()}catch(x){dq.err(x)}}};
      document.querySelectorAll('.delete-owner-payment').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this manually recorded payment?'))return;try{const {error}=await dq.db.from('owner_payments').delete().eq('id',b.dataset.id);if(error)throw error;dq.toast('Payment deleted.');adminFinance()}catch(x){dq.err(x)}});
    }

    async function settings(){const r=ctx.restaurant;content.innerHTML=head('Restaurant settings','Only the owner can change company and bill settings.')+`<div class="card" style="max-width:720px"><form id="settings-form" class="auth-form"><label>Company name<input class="input" name="name" value="${dq.esc(r.name)}" required></label><label>Tax percentage<input class="input" name="tax_percent" type="number" min="0" max="100" step="0.001" value="${r.tax_percent??''}" placeholder="—"></label><div class="field-row"><label>Service charge type<select name="service_charge_kind"><option value="">—</option><option value="percentage" ${r.service_charge_kind==='percentage'?'selected':''}>Percentage</option><option value="fixed" ${r.service_charge_kind==='fixed'?'selected':''}>Fixed USD amount</option></select></label><label>Service charge value<input class="input" name="service_charge_value" type="number" min="0" step="0.01" value="${r.service_charge_value??''}" placeholder="—"></label></div><label>Currency<input class="input" value="USD" disabled></label><button class="btn" type="submit">Save settings</button></form></div>`;document.getElementById('settings-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button'),x=dq.formData(e.target),payload={name:x.name.trim(),tax_percent:x.tax_percent===''?null:Number(x.tax_percent),service_charge_kind:x.service_charge_kind||null,service_charge_value:x.service_charge_value===''?null:Number(x.service_charge_value)};dq.setBusy(b,true);try{const {error}=await dq.db.from('restaurants').update(payload).eq('id',rid);if(error)throw error;dq.toast('Settings saved.');setTimeout(()=>location.reload(),500)}catch(x){dq.err(x)}finally{dq.setBusy(b,false)}}}

    const handlers={dashboard,companies,'admin-finance':adminFinance,tables,orders,menu,staff,finance,settings};await handlers[page]();
    if(page==='orders')dq.db.channel('live-orders').on('postgres_changes',{event:'*',schema:'public',table:'orders',filter:`restaurant_id=eq.${rid}`},()=>{clearTimeout(window.__orderRefresh);window.__orderRefresh=setTimeout(orders,300)}).subscribe();
  }catch(error){console.error(error);const app=document.getElementById('app');app.className='expired';app.innerHTML=`<div class="card"><h1>Something needs attention</h1><p class="muted">${dq.esc(dq.friendlyError(error))}</p><a class="btn" href="index.html">Back to sign in</a></div>`}
})();
