(async function(){
  try{
    const ctx=await dq.requireAuth();if(!ctx)return;const role=dq.roleOf(ctx);if(!['owner','manager','waiter','cashier'].includes(role)){location.replace('dashboard.html');return}dq.shell('approvals',ctx);
    const content=document.getElementById('content'),rid=ctx.restaurant.id,reviewer=['owner','manager'].includes(role),q=async request=>{const {data,error}=await request;if(error)throw error;return data||[]};let branch;
    async function render(){
      const branches=await q(dq.db.from('restaurant_branches').select('*').eq('restaurant_id',rid).eq('active',true).order('is_default',{ascending:false}));branch=branches[0];
      const [requests,rules]=await Promise.all([q(dq.db.from('approval_requests').select('*').eq('branch_id',branch.id).order('created_at',{ascending:false}).limit(100)),reviewer?q(dq.db.from('approval_rules').select('*').eq('branch_id',branch.id).order('action_type')):Promise.resolve([])]),userIds=[...new Set(requests.flatMap(x=>[x.requested_by,x.reviewed_by]).filter(Boolean))],profiles=userIds.length?await q(dq.db.from('profiles').select('id,full_name,email').in('id',userIds)):[],name=id=>{const p=profiles.find(x=>x.id===id);return p?.full_name||p?.email||'Team member'},pending=requests.filter(x=>x.status==='pending');
      content.innerHTML=`<div class="section-head"><div><span class="eyebrow">Release 3 controls</span><h1>${reviewer?'Manager approval queue':'Approval requests'}</h1><p>High-risk discounts, voids, refunds and cash corrections leave a reasoned audit trail.</p></div><button class="btn" id="request-approval">New request</button></div><div class="metrics"><div class="metric"><small>Awaiting decision</small><strong>${pending.length}</strong></div><div class="metric"><small>Approved</small><strong>${requests.filter(x=>x.status==='approved').length}</strong></div><div class="metric"><small>Rejected</small><strong>${requests.filter(x=>x.status==='rejected').length}</strong></div><div class="metric"><small>Rules active</small><strong>${rules.filter(x=>x.active).length}</strong></div></div>
      ${reviewer?`<section class="card r3-panel"><div class="section-subhead"><div><span class="eyebrow">Approval policy</span><h2>Manager thresholds</h2><p>Use these limits as the restaurant’s control policy. Requests and decisions remain server-audited.</p></div></div><div class="approval-rule-grid">${['discount','void','refund','cash_adjustment'].map(type=>{const r=rules.find(x=>x.action_type===type);return `<article><strong>${dq.esc(type.replace('_',' '))}</strong><span>${r?.threshold_amount!=null?`Above ${dq.money(r.threshold_amount)}`:'Any amount'}${r?.threshold_percent!=null?` · above ${r.threshold_percent}%`:''}</span><button class="btn ghost small edit-rule" data-type="${type}">${r?'Edit rule':'Set rule'}</button></article>`}).join('')}</div></section>`:''}
      <section class="card r3-panel"><div class="section-subhead"><div><span class="eyebrow">Decision queue</span><h2>Requests</h2><p>An approval records authority; it does not silently change a payment or order.</p></div></div><div class="approval-list">${requests.map(r=>`<article class="approval-card ${r.status}"><div class="approval-symbol">${r.status==='pending'?'!':r.status==='approved'?'✓':'×'}</div><div class="approval-copy"><div><span class="badge ${r.status==='approved'?'ready':r.status==='pending'?'pending':'inactive'}">${r.status}</span><strong>${dq.esc(r.request_type.replaceAll('_',' '))}</strong></div><p>${dq.esc(r.reason)}</p><small>Requested by ${dq.esc(name(r.requested_by))} · ${dq.date(r.created_at)} · ${dq.esc(r.entity_type)}</small>${r.reviewed_at?`<small>Reviewed by ${dq.esc(name(r.reviewed_by))} · ${dq.date(r.reviewed_at)}${r.review_reason?` · ${dq.esc(r.review_reason)}`:''}</small>`:''}</div>${reviewer&&r.status==='pending'?`<div class="approval-actions"><button class="btn small approve-request" data-id="${r.id}">Approve</button><button class="btn ghost small reject-request" data-id="${r.id}">Reject</button></div>`:''}</article>`).join('')||'<div class="empty">No approval requests yet.</div>'}</div></section>`;
      bind(rules);
    }
    function bind(rules){
      document.getElementById('request-approval').onclick=()=>{dq.modal('Request manager approval',`<form id="approval-request-form"><label>Request type<select name="request_kind"><option value="discount">Discount</option><option value="void">Void item</option><option value="refund">Refund</option><option value="cash_adjustment">Cash adjustment</option><option value="payment_correction">Payment correction</option><option value="receipt_correction">Receipt correction</option><option value="business_day_reopen">Reopen business day</option></select></label><label>Related record ID<input class="input" name="target_entity" placeholder="Optional bill, order, item or day UUID"></label><label>Reason<textarea name="request_reason" rows="4" minlength="3" required></textarea></label><label>Requested amount<input class="input" type="number" min="0" step="0.01" name="amount"></label><button class="btn">Send for approval</button></form>`);document.getElementById('approval-request-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button'),v=dq.formData(e.target);dq.setBusy(b,true,'Sending…');try{const {error}=await dq.db.rpc('create_approval_request',{target_restaurant:rid,target_branch:branch.id,request_kind:v.request_kind,entity_kind:v.request_kind,target_entity:v.target_entity||null,request_reason:v.request_reason,request_payload:{amount:v.amount?Number(v.amount):null}});if(error)throw error;dq.closeModal();dq.toast('Approval request sent.');render()}catch(error){dq.err(error)}finally{dq.setBusy(b,false)}}};
      document.querySelectorAll('.approve-request').forEach(b=>b.onclick=()=>review(b.dataset.id,'approved'));document.querySelectorAll('.reject-request').forEach(b=>b.onclick=()=>review(b.dataset.id,'rejected'));
      document.querySelectorAll('.edit-rule').forEach(b=>b.onclick=()=>{const rule=rules.find(x=>x.action_type===b.dataset.type);dq.modal(`Approval rule · ${b.dataset.type.replace('_',' ')}`,`<form id="approval-rule-form"><label>Amount threshold (USD)<input class="input" type="number" min="0" step="0.01" name="amount_threshold" value="${rule?.threshold_amount??''}" placeholder="Blank means any amount"></label><label>Percentage threshold<input class="input" type="number" min="0" max="100" step="0.001" name="percent_threshold" value="${rule?.threshold_percent??''}" placeholder="Optional"></label><label class="check"><input type="checkbox" name="rule_active" ${rule?.active!==false?'checked':''}> Rule active</label><button class="btn">Save rule</button></form>`);document.getElementById('approval-rule-form').onsubmit=async e=>{e.preventDefault();const v=dq.formData(e.target);try{const {error}=await dq.db.rpc('save_approval_rule',{target_branch:branch.id,action_kind:b.dataset.type,amount_threshold:v.amount_threshold===''?null:Number(v.amount_threshold),percent_threshold:v.percent_threshold===''?null:Number(v.percent_threshold),rule_active:Boolean(v.rule_active)});if(error)throw error;dq.closeModal();dq.toast('Approval rule saved.');render()}catch(error){dq.err(error)}}});
    }
    function review(id,decision){dq.modal(`${decision==='approved'?'Approve':'Reject'} request`, `<form id="approval-review-form"><p>${decision==='approved'?'Confirm that a manager authorises this request.':'Explain why this request is not authorised.'}</p><label>Decision note<textarea name="decision_reason" rows="3" ${decision==='rejected'?'required':''}></textarea></label><button class="btn ${decision==='rejected'?'danger':''}">${decision==='approved'?'Approve request':'Reject request'}</button></form>`);document.getElementById('approval-review-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');dq.setBusy(b,true);try{const {error}=await dq.db.rpc('review_approval_request',{target_request:id,decision,decision_reason:e.target.decision_reason.value||null});if(error)throw error;dq.closeModal();dq.toast(`Request ${decision}.`);render()}catch(error){dq.err(error)}finally{dq.setBusy(b,false)}}}
    await render();const channel=dq.db.channel(`release3-approvals-${rid}`).on('postgres_changes',{event:'*',schema:'public',table:'approval_requests',filter:`restaurant_id=eq.${rid}`},render).on('postgres_changes',{event:'*',schema:'public',table:'approval_rules',filter:`restaurant_id=eq.${rid}`},render).subscribe();window.addEventListener('beforeunload',()=>dq.db.removeChannel(channel));
  }catch(error){const content=document.getElementById('content')||document.getElementById('app');content.innerHTML=`<div class="empty">${dq.esc(dq.friendlyError(error))}</div>`;dq.err(error)}
})();
