(async function(){
  try{
    const ctx=await dq.requireAuth();if(!ctx)return;const role=dq.roleOf(ctx);if(!['owner','manager','waiter','cashier'].includes(role)){location.replace('dashboard.html');return}dq.shell('billing',ctx);
    const content=document.getElementById('content'),rid=ctx.restaurant.id,q=async request=>{const {data,error}=await request;if(error)throw error;return data||[]};let branch,methods=[],currencies=[];
    async function render(){
      const branches=await q(dq.db.from('restaurant_branches').select('*').eq('restaurant_id',rid).eq('active',true).order('is_default',{ascending:false}));branch=branches[0];
      const [sessions,tables,splitRows,methodRows,currencyRows]=await Promise.all([q(dq.db.from('table_sessions').select('*').eq('branch_id',branch.id).neq('status','closed').order('opened_at')),q(dq.db.from('physical_tables').select('*').eq('branch_id',branch.id)),q(dq.db.from('bill_splits').select('*').eq('branch_id',branch.id).neq('status','cancelled').order('split_number')),q(dq.db.from('restaurant_payment_methods').select('*').eq('branch_id',branch.id).eq('active',true).order('sort_order')),q(dq.db.from('branch_currencies').select('*').eq('branch_id',branch.id).eq('enabled',true).order('is_base',{ascending:false}))]);methods=methodRows;currencies=currencyRows;
      const cards=await Promise.all(sessions.map(async session=>{const sessionSplits=splitRows.filter(x=>x.session_id===session.id),table=tables.find(x=>x.id===session.table_id),orders=await q(dq.db.from('orders').select('*').eq('session_id',session.id).not('status','in','(pending,rejected)').order('created_at')),orderIds=orders.map(x=>x.id),items=orderIds.length?await q(dq.db.from('order_items').select('*').in('order_id',orderIds).is('voided_at',null)):[];return {session,sessionSplits,table,items}}));
      content.innerHTML=`<div class="section-head"><div><span class="eyebrow">Release 3 billing</span><h1>Split bills</h1><p>Divide a table equally or assign ordered items to individual guest bills. The table closes after every split is paid.</p></div><span class="badge active">Offline payments only</span></div><div class="metrics"><div class="metric"><small>Open tables</small><strong>${sessions.length}</strong></div><div class="metric"><small>Split tables</small><strong>${cards.filter(x=>x.sessionSplits.length).length}</strong></div><div class="metric"><small>Open guest bills</small><strong>${splitRows.filter(x=>x.status==='open').length}</strong></div><div class="metric"><small>Paid guest bills</small><strong>${splitRows.filter(x=>x.status==='paid').length}</strong></div></div><div class="split-table-list">${cards.map(card=>{const paid=card.sessionSplits.filter(x=>x.status==='paid').length,total=card.sessionSplits.reduce((s,x)=>s+Number(x.total),0);return `<section class="card split-table-card"><div class="split-table-head"><div><span class="eyebrow">Table</span><h2>${dq.esc(card.table?.label||'Table')}</h2><p>${card.items.length} billable line${card.items.length===1?'':'s'} · ${dq.esc(card.session.assigned_waiter_name||'No waiter assigned')}</p></div>${card.sessionSplits.length?`<div class="split-progress"><strong>${paid}/${card.sessionSplits.length}</strong><span>paid</span></div>`:`<button class="btn create-split" data-session="${card.session.id}">Split this bill</button>`}</div>${card.sessionSplits.length?`<div class="guest-bill-grid">${card.sessionSplits.map(s=>`<article class="guest-bill ${s.status}"><header><div><small>Bill ${s.split_number}</small><strong>${dq.esc(s.label)}</strong></div><span class="badge ${s.status==='paid'?'ready':'pending'}">${s.status}</span></header><div class="guest-bill-total"><span>Total</span><strong>${dq.money(s.total)}</strong></div><div class="guest-bill-breakdown"><span>Subtotal ${dq.money(s.subtotal)}</span><span>Tax & service ${dq.money(Number(s.tax_total)+Number(s.service_total))}</span></div>${s.status==='open'?`<button class="btn pay-split" data-id="${s.id}">Record payment</button>`:`<span class="paid-stamp">Paid ${dq.date(s.paid_at)}</span>`}</article>`).join('')}</div><div class="split-footer"><strong>Table total ${dq.money(total)}</strong>${paid===0?`<button class="btn ghost small cancel-splits" data-session="${card.session.id}">Cancel split plan</button>`:''}</div>`:`<div class="split-empty"><span>One normal bill is still available from Tables & QR.</span><small>Use splitting only when guests want separate bills.</small></div>`}</section>`}).join('')||'<div class="card empty">No open tables are available for billing.</div>'}</div>`;
      document.querySelectorAll('.create-split').forEach(b=>b.onclick=()=>openPlan(cards.find(x=>x.session.id===b.dataset.session)));
      document.querySelectorAll('.pay-split').forEach(b=>b.onclick=()=>openPayment(splitRows.find(x=>x.id===b.dataset.id),cards.find(x=>x.session.id===splitRows.find(s=>s.id===b.dataset.id)?.session_id)));
      document.querySelectorAll('.cancel-splits').forEach(b=>b.onclick=async()=>{if(!confirm('Cancel this split plan and return to one normal bill?'))return;try{const {error}=await dq.db.rpc('cancel_bill_split_plan',{target_session:b.dataset.session});if(error)throw error;dq.toast('Split plan cancelled.');render()}catch(error){dq.err(error)}});
    }
    function openPlan(card){
      if(card.items.length<2){dq.toast('At least two billable item lines are needed to split by item. Equal splitting is still available.','error')}
      dq.modal(`Split bill · ${card.table?.label||'Table'}`,`<form id="split-plan-form"><div class="split-mode-picker"><label><input type="radio" name="split_mode" value="equal" checked> <strong>Equal shares</strong><small>Divide the final total evenly.</small></label><label><input type="radio" name="split_mode" value="items"> <strong>By ordered item</strong><small>Choose which guest pays for each line.</small></label></div><label>Number of guest bills<select name="guest_count">${Array.from({length:9},(_,i)=>`<option value="${i+2}">${i+2} guests</option>`).join('')}</select></label><div id="item-assignment" hidden></div><button class="btn">Create split bills</button></form>`);
      const form=document.getElementById('split-plan-form'),box=document.getElementById('item-assignment');function draw(){const mode=form.split_mode.value,count=Number(form.guest_count.value);box.hidden=mode!=='items';box.innerHTML=mode==='items'?`<p class="muted">Every item must belong to one guest.</p>${card.items.map(item=>`<label class="split-item-assignment"><span><strong>${item.quantity} × ${dq.esc(item.item_name_snapshot)}</strong><small>${dq.money(Number(item.quantity)*Number(item.unit_price_snapshot))}</small></span><select name="item_${item.id}">${Array.from({length:count},(_,i)=>`<option value="${i}">Guest ${i+1}</option>`).join('')}</select></label>`).join('')}`:''}form.querySelectorAll('[name="split_mode"]').forEach(x=>x.onchange=draw);form.guest_count.onchange=draw;draw();
      form.onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button'),mode=form.split_mode.value,count=Number(form.guest_count.value),assignments=mode==='items'?Array.from({length:count},(_,i)=>({label:`Guest ${i+1}`,item_ids:card.items.filter(item=>form[`item_${item.id}`].value===String(i)).map(item=>item.id)})):[];if(mode==='items'&&assignments.some(x=>!x.item_ids.length)){dq.toast('Every guest bill needs at least one item.','error');return}dq.setBusy(b,true,'Creating…');try{const {error}=await dq.db.rpc('create_bill_split_plan',{target_session:card.session.id,split_mode:mode,equal_split_count:mode==='equal'?count:null,item_assignments:assignments});if(error)throw error;dq.closeModal();dq.toast('Split bills created.');render()}catch(error){dq.err(error)}finally{dq.setBusy(b,false)}};
    }
    function openPayment(split,card){
      const key=crypto.randomUUID();dq.modal(`Record payment · ${split.label}`,`<form id="split-payment-form"><div class="checkout-preview"><div class="checkout-total"><span>Amount due</span><strong>${dq.money(split.balance)}</strong></div></div><label>Payment method<select name="payment_method_code" required>${methods.map(m=>`<option value="${m.method_code}">${dq.esc(m.display_name)}</option>`).join('')}</select></label><label>Payment currency<select name="payment_currency" required>${currencies.map(c=>`<option value="${c.currency_code}">${c.currency_code}</option>`).join('')}</select></label><div id="split-conversion" hidden><div class="field-row"><label>Amount received<input class="input" type="number" min="0" step="0.01" name="tendered_amount"></label><label>Rate to USD<input class="input" type="number" min="0.00000001" step="0.00000001" name="exchange_rate_to_bill"></label></div></div><label>Payment reference<input class="input" name="payment_reference"></label><button class="btn">Record ${dq.money(split.balance)} payment</button></form>`);const form=document.getElementById('split-payment-form'),conversion=document.getElementById('split-conversion');function update(){const nonBase=form.payment_currency.value!=='USD';conversion.hidden=!nonBase;form.tendered_amount.required=nonBase;form.exchange_rate_to_bill.required=nonBase;if(nonBase)form.exchange_rate_to_bill.value=currencies.find(x=>x.currency_code===form.payment_currency.value)?.rate_to_base||''}form.payment_currency.onchange=update;update();form.onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button'),v=dq.formData(e.target);dq.setBusy(b,true,'Recording…');try{const {data,error}=await dq.db.rpc('record_split_payment',{target_split:split.id,payment_method_code:v.payment_method_code,payment_currency:v.payment_currency,payment_reference:v.payment_reference||null,tendered_amount:v.payment_currency==='USD'?null:Number(v.tendered_amount),exchange_rate_to_bill:v.payment_currency==='USD'?1:Number(v.exchange_rate_to_bill),idempotency_key:key});if(error)throw error;dq.closeModal();dq.modal(data.table_closed?'Table bill completed':'Guest bill paid',`<div class="receipt"><div class="line"><span>Table</span><strong>${dq.esc(card?.table?.label||'—')}</strong></div><div class="line"><span>Guest bill</span><strong>${dq.esc(split.label)}</strong></div><div class="line total"><span>Paid</span><strong>${dq.money(data.amount,data.currency)}</strong></div><div class="line"><span>Method</span><span>${dq.esc(data.payment_method)}</span></div></div><p>${data.table_closed?'Every guest bill is paid. The table is closed and its QR code has expired.':`${data.remaining_splits} guest bill${data.remaining_splits===1?' remains':'s remain'}.`}</p><button class="btn no-print" onclick="window.print()">Print</button>`);render()}catch(error){dq.err(error)}finally{dq.setBusy(b,false)}};
    }
    await render();const channel=dq.db.channel(`release3-billing-${rid}`).on('postgres_changes',{event:'*',schema:'public',table:'bill_splits',filter:`restaurant_id=eq.${rid}`},render).on('postgres_changes',{event:'*',schema:'public',table:'table_sessions',filter:`restaurant_id=eq.${rid}`},render).subscribe();window.addEventListener('beforeunload',()=>dq.db.removeChannel(channel));
  }catch(error){const content=document.getElementById('content')||document.getElementById('app');content.innerHTML=`<div class="empty">${dq.esc(dq.friendlyError(error))}</div>`;dq.err(error)}
})();
