(async function(){
  const token=new URLSearchParams(location.search).get('token'),app=document.getElementById('customer-app');let session,cart={};
  if(!token){location.replace('session-ended.html');return}
  try{const {data,error}=await dq.db.rpc('get_public_session',{token});if(error)throw error;if(!data){location.replace('session-ended.html');return}session=data;render()}catch(error){app.innerHTML=`<div class="empty">${dq.esc(dq.friendlyError(error))}</div>`}

  function render(){
    const scrollPosition=window.scrollY,disabled=session.session_status==='bill_requested',groups=session.categories.map(c=>({id:c.id,name:c.name,items:session.items.filter(i=>i.category_id===c.id)})).filter(g=>g.items.length),uncategorized=session.items.filter(i=>!i.category_id);if(uncategorized.length)groups.push({id:'uncategorized',name:'Other',items:uncategorized});
    const heroImage=session.items.find(i=>i.image_url)?.image_url;document.getElementById('customer-company').textContent=session.restaurant_name;document.title=session.restaurant_name+' menu';
    app.innerHTML=`<section class="customer-hero"><div class="customer-hero-copy"><div class="eyebrow">Welcome to</div><h1>${dq.esc(session.restaurant_name)}</h1><div class="ornament"><span></span>✦<span></span></div><p>Browse the menu, choose your favourites, and order directly from your table.</p><button class="btn hero-menu-button" id="view-menu">View menu</button>${disabled?'<div class="form-success">The bill has been requested. Ask your waiter if you need anything else.</div>':''}</div><div class="customer-hero-visual ${heroImage?'has-image':''}" ${heroImage?`style="background-image:url('${dq.esc(heroImage)}')"`:''}><div class="plate-mark">Dine<br><span>well</span></div></div></section>${groups.length?`<nav class="category-tabs" id="menu-navigation">${groups.map((g,index)=>`<button class="${index===0?'active':''}" data-target="category-${g.id}">${dq.esc(g.name)}</button>`).join('')}</nav><div class="customer-category-list">${groups.map(g=>`<section class="customer-category" id="category-${g.id}"><div class="category-heading"><div><span class="eyebrow">Explore</span><h2>${dq.esc(g.name)}</h2></div><span class="muted">${g.items.length} ${g.items.length===1?'item':'items'}</span></div><div class="customer-menu">${itemsHtml(g.items,disabled)}</div></section>`).join('')}</div>`:'<div class="empty">The menu is being prepared. Please ask your waiter for assistance.</div>'}<footer class="restaurant-footer"><div><strong>${dq.esc(session.restaurant_name)}</strong><p>Browse, order, and enjoy.</p></div><small>© ${new Date().getFullYear()} ${dq.esc(session.restaurant_name)} · Digital ordering by DineQR</small></footer><div class="cart-bar"><button class="cart-button" id="open-cart" ${Object.keys(cart).length?'':'disabled'}><span>View order · ${count()} items</span><span>${dq.money(total(),session.currency)}</span></button></div>`;
    app.querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>{app.querySelectorAll('[data-target]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.target)?.scrollIntoView({behavior:'smooth',block:'start'})});document.getElementById('view-menu')?.addEventListener('click',()=>document.getElementById('menu-navigation')?.scrollIntoView({behavior:'smooth'}));bindItems();document.getElementById('open-cart').onclick=showCart;document.getElementById('request-bill').disabled=disabled;if(scrollPosition)setTimeout(()=>window.scrollTo(0,scrollPosition),0)
  }
  function itemsHtml(items,disabled){return items.map(i=>`<article class="menu-item customer-menu-row">${i.image_url?`<img class="customer-item-image" src="${dq.esc(i.image_url)}" alt="${dq.esc(i.name)}">`:'<div class="customer-item-image placeholder">DineQR</div>'}<div class="menu-item-copy"><h3>${dq.esc(i.name)}</h3><p>${dq.esc(i.description||'')}</p></div><div class="menu-item-buy"><span class="price">${dq.money(i.price,session.currency)}</span><div class="qty"><button data-minus="${i.id}" ${!cart[i.id]?'disabled':''} aria-label="Remove one ${dq.esc(i.name)}">−</button><strong>${cart[i.id]||0}</strong><button data-plus="${i.id}" ${disabled?'disabled':''} aria-label="Add one ${dq.esc(i.name)}">+</button></div></div></article>`).join('')}
  function bindItems(){document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{cart[b.dataset.plus]=(cart[b.dataset.plus]||0)+1;render()});document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{const id=b.dataset.minus;cart[id]-=1;if(cart[id]<=0)delete cart[id];render()})}
  function count(){return Object.values(cart).reduce((a,b)=>a+b,0)}
  function total(){return Object.entries(cart).reduce((sum,[id,quantity])=>sum+Number(session.items.find(i=>i.id===id)?.price||0)*quantity,0)}
  function showCart(){const rows=Object.entries(cart).map(([id,quantity])=>{const item=session.items.find(x=>x.id===id);return `<div class="cart-line"><div><strong>${quantity} × ${dq.esc(item.name)}</strong><label style="margin-top:.5rem;font-weight:400">Special instructions<textarea rows="2" data-note="${id}" placeholder="Optional"></textarea></label></div><strong>${dq.money(item.price*quantity,session.currency)}</strong></div>`}).join('');dq.modal('Your order',`<div class="cart-list">${rows}<div class="receipt line total"><span>Total</span><span>${dq.money(total(),session.currency)}</span></div></div><p class="muted">Your waiter must accept this order before the kitchen prepares it.</p><button class="btn" id="place-order" style="width:100%">Place order</button>`);document.getElementById('place-order').onclick=placeOrder}
  async function placeOrder(){const button=document.getElementById('place-order'),items=Object.entries(cart).map(([id,quantity])=>({menu_item_id:id,quantity,instructions:document.querySelector(`[data-note="${id}"]`)?.value||''}));dq.setBusy(button,true,'Sending order…');try{const {data,error}=await dq.db.rpc('place_customer_order',{token,items});if(error)throw error;cart={};dq.closeModal();dq.modal('Order sent',`<div style="text-align:center;padding:1rem"><div style="font-size:3rem">✓</div><h2>Order received</h2><p class="muted">Order total: ${dq.money(data.total,session.currency)}. Your waiter will review it.</p><button class="btn" onclick="dq.closeModal()">Continue browsing</button></div>`);render()}catch(error){dq.err(error)}finally{dq.setBusy(button,false)}}
  async function request(kind){const button=document.getElementById(kind==='bill'?'request-bill':'call-waiter');dq.setBusy(button,true,'Sending…');try{const {error}=await dq.db.rpc('create_customer_request',{token,request_kind:kind});if(error)throw error;dq.toast(kind==='bill'?'Bill requested.':'A waiter has been called.');if(kind==='bill'){session.session_status='bill_requested';render()}}catch(error){dq.err(error)}finally{dq.setBusy(button,false)}}
  document.getElementById('call-waiter').onclick=()=>request('waiter');document.getElementById('request-bill').onclick=()=>request('bill');
})();
