(async function(){
  try{
    const ctx=await dq.requireAuth();if(!ctx)return;const role=dq.roleOf(ctx);if(!['owner','manager','waiter'].includes(role)){location.replace('dashboard.html');return}dq.shell('floor',ctx);
    const content=document.getElementById('content'),rid=ctx.restaurant.id,canEdit=['owner','manager'].includes(role),operator=ctx.waiter_operator?.id||null;let selectedArea=null,editing=false,refreshTimer;
    const q=async request=>{const {data,error}=await request;if(error)throw error;return data||[]},money=(v,c='USD')=>dq.money(v||0,c);
    const elapsed=value=>{const mins=Math.max(0,Math.floor((Date.now()-new Date(value))/60000));return mins<60?`${mins}m`:`${Math.floor(mins/60)}h ${mins%60}m`};
    async function load(){
      const [areas,tables,sessions,orders,items,sections,links,waiters,transfers,alerts]=await Promise.all([
        q(dq.db.from('floor_areas').select('*').eq('restaurant_id',rid).eq('active',true).order('sort_order')),q(dq.db.from('physical_tables').select('*').eq('restaurant_id',rid).eq('active',true)),q(dq.db.from('table_sessions').select('*').eq('restaurant_id',rid).neq('status','closed')),q(dq.db.from('orders').select('id,session_id,status').eq('restaurant_id',rid).in('status',['pending','accepted','preparing','ready'])),q(dq.db.from('order_items').select('order_id,preparation_status,voided_at')),q(dq.db.from('waiter_sections').select('*').eq('restaurant_id',rid).eq('active',true)),q(dq.db.from('waiter_section_tables').select('*')),q(dq.db.from('waiter_profiles').select('id,full_name').eq('restaurant_id',rid).eq('active',true).order('full_name')),q(dq.db.from('table_transfers').select('*').eq('restaurant_id',rid).order('transferred_at',{ascending:false}).limit(100)),q(dq.db.from('waiter_ready_alerts').select('*').eq('restaurant_id',rid).is('acknowledged_at',null).order('created_at'))
      ]);if(!selectedArea||!areas.some(a=>a.id===selectedArea))selectedArea=areas[0]?.id||null;
      const {data:floorTotals,error:floorTotalsError}=await dq.db.rpc('get_live_floor_totals',{target_restaurant:rid});if(floorTotalsError)throw floorTotalsError;const sessionByTable=Object.fromEntries(sessions.map(s=>[s.table_id,s])),orderById=Object.fromEntries(orders.map(o=>[o.id,o])),billBySession=Object.fromEntries((floorTotals||[]).map(b=>[b.session_id,b])),sectionByTable={};links.forEach(l=>{const s=sections.find(x=>x.id===l.section_id);if(s)sectionByTable[l.table_id]=s});
      const tableState=t=>{const s=sessionByTable[t.id];if(!s)return{key:'available',label:'Available'};const os=orders.filter(o=>o.session_id===s.id),its=items.filter(i=>orderById[i.order_id]?.session_id===s.id&&!i.voided_at);if(s.status==='bill_requested')return{key:'bill',label:'Bill requested'};if(its.some(i=>i.preparation_status==='ready'))return{key:'ready',label:'Ready to serve'};if(its.some(i=>i.preparation_status==='preparing'))return{key:'preparing',label:'Preparing'};if(os.length)return{key:'ordered',label:'Order sent'};return{key:'seated',label:'Seated'}};
      const visibleTables=tables.filter(t=>!selectedArea||t.floor_area_id===selectedArea).filter(t=>role!=='waiter'||!operator||sessionByTable[t.id]?.assigned_waiter_profile_id===operator||sectionByTable[t.id]?.waiter_profile_id===operator);
      content.innerHTML=`<div class="section-head floor-heading"><div><span class="eyebrow">Live dining room</span><h1>Floor</h1><p>See every table, preparation delay and service handoff in one place.</p></div><div class="actions">${canEdit?`<button class="btn ghost" id="sections">Waiter sections</button><button class="btn ghost" id="add-area">Add area</button><button class="btn" id="edit-layout">${editing?'Finish layout':'Edit layout'}</button>`:''}</div></div><nav class="floor-tabs">${areas.map(a=>`<button class="${a.id===selectedArea?'active':''}" data-area="${a.id}">${dq.esc(a.name)}<small>${tables.filter(t=>t.floor_area_id===a.id).length}</small></button>`).join('')}</nav><div class="floor-legend"><span data-state="available">Available</span><span data-state="seated">Seated</span><span data-state="preparing">Preparing</span><span data-state="ready">Ready</span><span data-state="bill">Bill requested</span></div>${areas.length?`<div class="floor-canvas ${editing?'editing':''}" style="--canvas-w:${areas.find(a=>a.id===selectedArea)?.canvas_width||1200};--canvas-h:${areas.find(a=>a.id===selectedArea)?.canvas_height||720};background:${areas.find(a=>a.id===selectedArea)?.background_color||'#f4ebdd'}">${visibleTables.map(t=>{const s=sessionByTable[t.id],state=tableState(t),section=sectionByTable[t.id],bill=s?billBySession[s.id]:null,readyCount=s?alerts.filter(a=>a.session_id===s.id).length:0;return `<article class="floor-table shape-${t.floor_shape} state-${state.key}" data-table="${t.id}" style="left:${t.floor_x}px;top:${t.floor_y}px;width:${t.floor_width}px;height:${t.floor_height}px;${section?`--section:${section.color}`:''}" tabindex="0"><div class="floor-table-top"><strong>${dq.esc(t.label)}</strong><span>${t.seats}</span></div><small>${state.label}</small>${s?`<div class="floor-table-facts"><span>${s.guest_count||'—'} guests</span><span>${elapsed(s.opened_at)}</span></div><div class="floor-table-waiter">${dq.esc(s.assigned_waiter_name||section?.name||'Unassigned')}</div>${bill?`<strong class="floor-bill">${money(bill.total)}</strong>`:''}${readyCount?`<b class="ready-count">${readyCount} ready</b>`:''}`:'<span class="floor-table-empty">Ready for guests</span>'}</article>`}).join('')}</div><div class="floor-mobile-list">${visibleTables.map(t=>{const s=sessionByTable[t.id],state=tableState(t),bill=s?billBySession[s.id]:null;return `<button class="floor-mobile-row state-${state.key}" data-open-table="${t.id}"><span><strong>${dq.esc(t.label)}</strong><small>${state.label}${s?` · ${elapsed(s.opened_at)}`:''}</small></span><span>${s?`${s.guest_count||'—'} guests · ${dq.esc(s.assigned_waiter_name||'Unassigned')}`:`${t.seats} seats`}${bill?`<strong>${money(bill.total)}</strong>`:''}</span></button>`}).join('')||'<div class="empty">No tables are assigned to this view.</div>'}</div>`:'<div class="empty">Add your first floor area to begin.</div>'}`;
      bind({areas,tables,sessions,sections,links,waiters,transfers,sessionByTable,sectionByTable});
    }
    function bind(data){
      document.querySelectorAll('[data-area]').forEach(b=>b.onclick=()=>{selectedArea=b.dataset.area;load()});document.getElementById('edit-layout')?.addEventListener('click',()=>{editing=!editing;load()});
      document.getElementById('add-area')?.addEventListener('click',()=>areaModal());document.getElementById('sections')?.addEventListener('click',()=>sectionModal(data));
      document.querySelectorAll('.floor-table').forEach(card=>{card.onclick=()=>editing?null:tableModal(card.dataset.table,data);card.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&!editing)tableModal(card.dataset.table,data)};if(editing)drag(card,data.areas.find(a=>a.id===selectedArea))});
      document.querySelectorAll('[data-open-table]').forEach(b=>b.onclick=()=>tableModal(b.dataset.openTable,data));
    }
    function drag(card,area){let start=null;card.onpointerdown=e=>{if(!editing)return;start={x:e.clientX,y:e.clientY,left:parseInt(card.style.left),top:parseInt(card.style.top)};card.setPointerCapture(e.pointerId)};card.onpointermove=e=>{if(!start)return;card.style.left=`${Math.max(0,Math.min(area.canvas_width-card.offsetWidth,start.left+e.clientX-start.x))}px`;card.style.top=`${Math.max(0,Math.min(area.canvas_height-card.offsetHeight,start.top+e.clientY-start.y))}px`};card.onpointerup=async()=>{if(!start)return;start=null;const table=card.dataset.table,{error}=await dq.db.rpc('update_table_floor_position',{target_table:table,target_area:selectedArea,x:parseInt(card.style.left),y:parseInt(card.style.top),table_width:card.offsetWidth,table_height:card.offsetHeight,table_shape:'rectangle'});if(error)dq.err(error);else dq.toast('Table position saved.')}}
    function areaModal(area){dq.modal(area?'Edit floor area':'Add floor area',`<form id="area-form"><label>Area name<input class="input" name="name" value="${dq.esc(area?.name||'')}" placeholder="Patio" required></label><label>Floor colour<input class="input" type="color" name="color" value="${area?.background_color||'#F4EBDD'}"></label><button class="btn">Save area</button></form>`);document.getElementById('area-form').onsubmit=async e=>{e.preventDefault();const x=dq.formData(e.target),{data,error}=await dq.db.rpc('save_floor_area',{target_area:area?.id||null,area_name:x.name,area_color:x.color});if(error)return dq.err(error);selectedArea=data;dq.closeModal();load()}}
    function sectionModal({areas,tables,sections,links,waiters}){dq.modal('Waiter sections',`<form id="section-form"><label>Section name<input class="input" name="name" placeholder="Front windows" required></label><div class="field-row"><label>Floor area<select name="area" required>${areas.map(a=>`<option value="${a.id}">${dq.esc(a.name)}</option>`).join('')}</select></label><label>Colour<input class="input" type="color" name="color" value="#A94732"></label></div><label>Assigned waiter<select name="waiter"><option value="">Unassigned</option>${waiters.map(w=>`<option value="${w.id}">${dq.esc(w.full_name)}</option>`).join('')}</select></label><fieldset><legend>Tables in this section</legend><div class="section-table-picker">${tables.map(t=>`<label><input type="checkbox" name="tables" value="${t.id}"><span>${dq.esc(t.label)}</span></label>`).join('')}</div></fieldset><button class="btn">Save section</button></form><div class="section-list">${sections.map(s=>`<div><i style="background:${s.color}"></i><strong>${dq.esc(s.name)}</strong><span>${dq.esc(waiters.find(w=>w.id===s.waiter_profile_id)?.full_name||'Unassigned')} · ${links.filter(l=>l.section_id===s.id).length} tables</span></div>`).join('')}</div>`);document.getElementById('section-form').onsubmit=async e=>{e.preventDefault();const x=dq.formData(e.target),ids=[...e.target.querySelectorAll('[name=tables]:checked')].map(i=>i.value),{error}=await dq.db.rpc('save_waiter_section',{target_section:null,section_name:x.name,section_color:x.color,target_area:x.area,target_waiter:x.waiter||null,table_ids:ids});if(error)return dq.err(error);dq.closeModal();load()}}
    function tableModal(id,{tables,sessions,waiters,transfers,sessionByTable}){const t=tables.find(x=>x.id===id),s=sessionByTable[id],history=s?transfers.filter(x=>x.session_id===s.id):[];dq.modal(t.label,`<div class="table-detail-panel"><div><span class="eyebrow">${s?'Open table':'Available'}</span><h2>${dq.esc(t.label)}</h2><p>${t.seats} seats${s?` · opened ${elapsed(s.opened_at)} ago`:''}</p></div>${s?`<dl><div><dt>Guests</dt><dd>${s.guest_count||'—'}</dd></div><div><dt>Waiter</dt><dd>${dq.esc(s.assigned_waiter_name||'Unassigned')}</dd></div></dl><div class="actions"><a class="btn" href="tables.html">Open table controls</a>${canEdit?`<button class="btn ghost" id="transfer-table">Transfer</button>`:''}</div>${history.length?`<div class="transfer-history"><h3>Transfer history</h3>${history.map(x=>`<div><span>${dq.date(x.transferred_at)}</span><strong>${dq.esc(tables.find(table=>table.id===x.from_table_id)?.label||'Previous table')} → ${dq.esc(tables.find(table=>table.id===x.to_table_id)?.label||'New table')}</strong><small>${dq.esc(x.reason)}</small></div>`).join('')}</div>`:''}`:'<a class="btn" href="tables.html">Open table</a>'}</div>`);document.getElementById('transfer-table')?.addEventListener('click',()=>transferModal(s,t,tables,sessions,waiters))}
    function transferModal(session,from,tables,sessions,waiters){const occupied=new Set(sessions.map(s=>s.table_id));dq.modal(`Transfer ${from.label}`,`<form id="transfer-form"><label>Destination table<select name="table" required><option value="">Choose available table</option>${tables.filter(t=>!occupied.has(t.id)).map(t=>`<option value="${t.id}">${dq.esc(t.label)} · ${t.seats} seats</option>`).join('')}</select></label><label>Waiter after transfer<select name="waiter"><option value="">Unassigned</option>${waiters.map(w=>`<option value="${w.id}" ${w.id===session.assigned_waiter_profile_id?'selected':''}>${dq.esc(w.full_name)}</option>`).join('')}</select></label><label>Reason<textarea name="reason" rows="3" minlength="3" required></textarea></label><button class="btn">Transfer table</button></form>`);document.getElementById('transfer-form').onsubmit=async e=>{e.preventDefault();const x=dq.formData(e.target),{error}=await dq.db.rpc('transfer_table_session',{target_session:session.id,target_table:x.table,target_waiter:x.waiter||null,transfer_reason:x.reason});if(error)return dq.err(error);dq.closeModal();dq.toast('Table transferred.');load()}}
    await load();const channel=dq.db.channel(`release2-floor-${rid}`).on('postgres_changes',{event:'*',schema:'public',table:'table_sessions',filter:`restaurant_id=eq.${rid}`},()=>schedule()).on('postgres_changes',{event:'*',schema:'public',table:'kds_tickets',filter:`restaurant_id=eq.${rid}`},()=>schedule()).on('postgres_changes',{event:'*',schema:'public',table:'waiter_ready_alerts',filter:`restaurant_id=eq.${rid}`},()=>schedule()).on('postgres_changes',{event:'*',schema:'public',table:'physical_tables',filter:`restaurant_id=eq.${rid}`},()=>schedule()).subscribe();function schedule(){clearTimeout(refreshTimer);refreshTimer=setTimeout(load,250)}window.addEventListener('beforeunload',()=>dq.db.removeChannel(channel));
  }catch(error){document.getElementById('content').innerHTML=`<div class="empty">${dq.esc(dq.friendlyError(error))}</div>`;dq.err(error)}
})();
