(async function(){
  try{
    const ctx=await dq.requireAuth();if(!ctx)return;const role=dq.roleOf(ctx);if(!['owner','manager'].includes(role)){location.replace('dashboard.html');return}dq.shell('reports',ctx);
    const content=document.getElementById('content'),rid=ctx.restaurant.id,q=async request=>{const {data,error}=await request;if(error)throw error;return data||[]},today=new Date(),to=today.toISOString().slice(0,10),from=new Date(today.getFullYear(),today.getMonth(),1).toISOString().slice(0,10);let branch,lastReport,lastRange;
    const maxOf=rows=>Math.max(1,...rows.map(x=>Number(x.sales??x.amount??x.value??0))),bars=(rows,label='sales')=>{const max=maxOf(rows);return `<div class="report-bars">${rows.map(x=>`<div><span>${dq.esc(x.label??x.business_date??String(x.hour).padStart(2,'0')+':00')}</span><i><b style="width:${Math.max(2,Number(x[label]??x.amount??0)/max*100)}%"></b></i><strong>${dq.money(x[label]??x.amount??0)}</strong></div>`).join('')||'<div class="empty">No data in this period.</div>'}</div>`};
    function table(title,rows,columns){return `<section class="card report-table"><h2>${title}</h2><div class="table-wrap"><table class="data-table"><thead><tr>${columns.map(c=>`<th>${c[0]}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${columns.map(c=>`<td>${c[2]==='money'?dq.money(row[c[1]]):dq.esc(row[c[1]]??'—')}</td>`).join('')}</tr>`).join('')}</tbody></table>${rows.length?'':'<div class="empty">No records in this period.</div>'}</div></section>`}
    async function render(start=from,end=to){
      if(!branch){const branches=await q(dq.db.from('restaurant_branches').select('*').eq('restaurant_id',rid).eq('active',true).order('is_default',{ascending:false}));branch=branches[0]}
      const {data,error}=await dq.db.rpc('get_release_3_reports',{target_branch:branch.id,date_from:start,date_to:end});if(error)throw error;lastReport=data;lastRange={start,end};const s=data.summary||{},labour=Number(s.labour_hours||0);
      content.innerHTML=`<div class="section-head reports-head"><div><span class="eyebrow">Release 3 intelligence</span><h1>Advanced reports</h1><p>Sales, payments, menu, staff, discounts, voids and cash variance in one controlled report.</p></div><form id="report-filter" class="analytics-filter"><label>From<input class="input" type="date" name="from" value="${start}" required></label><label>To<input class="input" type="date" name="to" value="${end}" required></label><button class="btn">Run report</button><button class="btn ghost" type="button" id="export-report">Export CSV</button><button class="btn ghost" type="button" onclick="window.print()">Print</button></form></div>
      <div class="metrics report-metrics"><div class="metric"><small>Gross sales</small><strong>${dq.money(s.gross_sales)}</strong></div><div class="metric"><small>Average bill</small><strong>${dq.money(s.average_bill)}</strong></div><div class="metric"><small>Transactions</small><strong>${s.transactions||0}</strong></div><div class="metric"><small>Cash variance</small><strong class="${Number(s.cash_variance)<0?'negative':''}">${dq.money(s.cash_variance)}</strong></div><div class="metric"><small>Discounts</small><strong>${dq.money(s.discounts)}</strong></div><div class="metric"><small>Voided lines</small><strong>${s.voids||0}</strong></div><div class="metric"><small>Labour hours</small><strong>${labour.toFixed(1)}h</strong></div></div>
      <div class="report-chart-grid"><section class="card"><h2>Sales by day</h2>${bars(data.daily_sales||[])}</section><section class="card"><h2>Payments by method</h2>${bars(data.payment_methods||[],'amount')}</section><section class="card"><h2>Sales by hour</h2>${bars(data.hourly_sales||[])}</section><section class="card"><h2>Top menu items</h2>${bars(data.top_items||[])}</section></div>
      <div class="report-table-grid">${table('Tables',data.table_sales||[],[['Table','label'],['Bills','bills'],['Sales','sales','money']])}${table('Waiters',data.waiter_sales||[],[['Waiter','label'],['Bills','bills'],['Sales','sales','money']])}${table('Discount usage',data.discounts||[],[['Discount','label'],['Uses','uses'],['Value','amount','money']])}${table('Voids & reasons',data.voids||[],[['Item','label'],['Lines','quantity'],['Value','value','money'],['Reason','reason']])}${table('Cashier reconciliations',data.cash_shifts||[],[['Business day','business_date'],['Cashier','cashier'],['Expected','expected_cash','money'],['Counted','counted_cash','money'],['Variance','variance','money'],['Status','status']])}${table('Staff attendance',data.staff_attendance||[],[['Staff','staff_name_snapshot'],['Role','role_snapshot'],['Scheduled','scheduled_start'],['Clocked in','clocked_in_at'],['Clocked out','clocked_out_at'],['Status','status']])}</div>`;
      document.getElementById('report-filter').onsubmit=e=>{e.preventDefault();render(e.target.from.value,e.target.to.value).catch(dq.err)};document.getElementById('export-report').onclick=exportCsv;
    }
    function exportCsv(){const rows=[['TafuraFlow advanced report',ctx.restaurant.name],['Period',`${lastRange.start} to ${lastRange.end}`],[],['Summary','Value'],...Object.entries(lastReport.summary||{}),[],['Payment method','Amount','Transactions'],...(lastReport.payment_methods||[]).map(x=>[x.label,x.amount,x.transactions]),[],['Business date','Sales','Bills'],...(lastReport.daily_sales||[]).map(x=>[x.business_date,x.sales,x.bills]),[],['Item','Quantity','Sales'],...(lastReport.top_items||[]).map(x=>[x.label,x.quantity,x.sales]),[],['Waiter','Bills','Sales'],...(lastReport.waiter_sales||[]).map(x=>[x.label,x.bills,x.sales]),[],['Void item','Quantity','Value','Reason'],...(lastReport.voids||[]).map(x=>[x.label,x.quantity,x.value,x.reason])],csv=rows.map(row=>row.map(value=>`"${String(value??'').replaceAll('"','""')}"`).join(',')).join('\r\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`tafuraflow-report-${lastRange.start}-${lastRange.end}.csv`;a.click();URL.revokeObjectURL(url)}
    await render();
  }catch(error){const content=document.getElementById('content')||document.getElementById('app');content.innerHTML=`<div class="empty">${dq.esc(dq.friendlyError(error))}</div>`;dq.err(error)}
})();
