(async function(){
  try{
    const ctx=await dq.requireAuth();if(!ctx)return;const role=dq.roleOf(ctx);if(!['kitchen','bar','owner','manager'].includes(role)){location.replace('dashboard.html');return}dq.shell('stations',ctx);
    const content=document.getElementById('content'),rid=ctx.restaurant.id,group=role==='bar'?'bar':'kitchen',canManage=['owner','manager'].includes(role);let selected=null,refreshTimer;
    const q=async request=>{const {data,error}=await request;if(error)throw error;return data||[]};
    const elapsed=value=>{const seconds=Math.max(0,Math.floor((Date.now()-new Date(value))/1000)),mins=Math.floor(seconds/60);return mins<60?`${String(mins).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`:`${Math.floor(mins/60)}h ${mins%60}m`};
    async function render(){
      const [stations,tickets,orders,items,sessions,tables,options]=await Promise.all([q(dq.db.from('prep_stations').select('*').eq('restaurant_id',rid).eq('station_group',group).eq('active',true).order('sort_order')),q(dq.db.from('kds_tickets').select('*').eq('restaurant_id',rid).in('status',['new','acknowledged','preparing','ready']).order('priority',{ascending:false}).order('created_at')),q(dq.db.from('orders').select('id,order_number,source').eq('restaurant_id',rid)),q(dq.db.from('order_items').select('*')),q(dq.db.from('table_sessions').select('id,table_id,assigned_waiter_name').eq('restaurant_id',rid)),q(dq.db.from('physical_tables').select('id,label').eq('restaurant_id',rid)),q(dq.db.from('order_item_modifiers').select('*'))]);if(!selected||!stations.some(s=>s.id===selected))selected=stations[0]?.id||null;
      const station=stations.find(s=>s.id===selected),orderMap=Object.fromEntries(orders.map(o=>[o.id,o])),tableMap=Object.fromEntries(tables.map(t=>[t.id,t.label])),sessionMap=Object.fromEntries(sessions.map(s=>[s.id,{...s,label:tableMap[s.table_id]||'Table'}])),rows=tickets.filter(t=>t.prep_station_id===selected);
      content.innerHTML=`<div class="section-head kds-heading"><div><span class="eyebrow">Live preparation</span><h1>${group==='bar'?'Bar':'Kitchen'} display</h1><p>Acknowledge every ticket, watch its timer, then alert the waiter when it is ready.</p></div><div class="kds-clock" id="kds-clock"></div></div><nav class="station-tabs">${stations.map(s=>`<button class="${s.id===selected?'active':''}" data-station="${s.id}" style="--station:${s.color}"><span></span>${dq.esc(s.name)}<small>${tickets.filter(t=>t.prep_station_id===s.id&&t.status!=='ready').length}</small></button>`).join('')}</nav>${station?`<div class="kds-lanes"><section><h2>New <span>${rows.filter(t=>['new','acknowledged'].includes(t.status)).length}</span></h2><div class="kds-board">${rows.filter(t=>['new','acknowledged'].includes(t.status)).map(t=>ticket(t,station,orderMap[t.order_id],items.filter(i=>i.order_id===t.order_id&&i.prep_station_id===selected&&!i.voided_at),sessionMap[t.session_id]||{},options)).join('')||'<div class="empty">No new tickets.</div>'}</div></section><section><h2>Preparing <span>${rows.filter(t=>t.status==='preparing').length}</span></h2><div class="kds-board">${rows.filter(t=>t.status==='preparing').map(t=>ticket(t,station,orderMap[t.order_id],items.filter(i=>i.order_id===t.order_id&&i.prep_station_id===selected&&!i.voided_at),sessionMap[t.session_id]||{},options)).join('')||'<div class="empty">Nothing preparing.</div>'}</div></section><section><h2>Ready <span>${rows.filter(t=>t.status==='ready').length}</span></h2><div class="kds-board">${rows.filter(t=>t.status==='ready').map(t=>ticket(t,station,orderMap[t.order_id],items.filter(i=>i.order_id===t.order_id&&i.prep_station_id===selected&&!i.voided_at),sessionMap[t.session_id]||{},options)).join('')||'<div class="empty">Nothing waiting for service.</div>'}</div></section></div>`:'<div class="empty">No active preparation stations.</div>'}`;bind();updateTimers();
    }
    function ticket(t,station,order,items,session,options){const age=(Date.now()-new Date(t.created_at))/60000,timerClass=age>=station.overdue_minutes?'late':age>=station.warning_minutes?'warning':'good';return `<article class="kds-ticket ${t.status} priority-${t.priority}" data-created="${t.created_at}"><div class="kds-ticket-head" style="--station:${station.color}"><div><span class="route-chip">${dq.esc(station.name)}</span><h2>${dq.esc(session.label||'Table')}</h2><p>Order #${order?.order_number||'—'} · ${dq.esc(session.assigned_waiter_name||'No waiter')}</p></div><strong class="ticket-timer ${timerClass}">${elapsed(t.created_at)}</strong></div>${t.priority!=='normal'?`<div class="priority-banner">${t.priority.toUpperCase()} PRIORITY</div>`:''}<div class="kds-ticket-items">${items.map(i=>{const mods=options.filter(x=>x.order_item_id===i.id);return `<div><strong>${i.quantity} × ${dq.esc(i.item_name_snapshot)}</strong>${mods.length?`<small>${mods.map(x=>dq.esc(x.modifier_name_snapshot)).join(' · ')}</small>`:''}${i.special_instructions?`<em>${dq.esc(i.special_instructions)}</em>`:''}<button class="sold-out-link" data-menu-item="${i.menu_item_id}" type="button">Mark sold out</button></div>`}).join('')}</div><div class="kds-ticket-actions">${t.status==='new'?`<button class="btn ticket-next" data-ticket="${t.id}" data-next="acknowledged">Acknowledge</button>`:t.status==='acknowledged'?`<button class="btn ticket-next" data-ticket="${t.id}" data-next="preparing">Start preparing</button>`:t.status==='preparing'?`<button class="btn ticket-next" data-ticket="${t.id}" data-next="ready">Mark ready</button>`:'<span class="badge ready">Waiter alerted</span>'}${canManage?`<select class="priority-select" data-ticket="${t.id}" aria-label="Ticket priority"><option value="normal" ${t.priority==='normal'?'selected':''}>Normal</option><option value="rush" ${t.priority==='rush'?'selected':''}>Rush</option><option value="vip" ${t.priority==='vip'?'selected':''}>VIP</option></select>`:''}</div></article>`}
    function bind(){document.querySelectorAll('[data-station]').forEach(b=>b.onclick=()=>{selected=b.dataset.station;render()});document.querySelectorAll('.ticket-next').forEach(b=>b.onclick=async()=>{dq.setBusy(b,true);const {error}=await dq.db.rpc('advance_kds_ticket',{target_ticket:b.dataset.ticket,next_status:b.dataset.next});if(error){dq.err(error);dq.setBusy(b,false)}else render()});document.querySelectorAll('.priority-select').forEach(s=>s.onchange=async()=>{const {error}=await dq.db.rpc('set_kds_priority',{target_ticket:s.dataset.ticket,new_priority:s.value});if(error)dq.err(error);else render()});document.querySelectorAll('.sold-out-link').forEach(b=>b.onclick=async()=>{if(!confirm('Mark this menu item sold out for customers?'))return;const {error}=await dq.db.rpc('set_menu_item_availability',{target_item:b.dataset.menuItem,new_status:'sold_out',snooze_until:null,remaining_quantity:null});if(error)dq.err(error);else dq.toast('Item marked sold out.')})}
    function updateTimers(){document.getElementById('kds-clock')&&(document.getElementById('kds-clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}));document.querySelectorAll('.kds-ticket').forEach(t=>{const timer=t.querySelector('.ticket-timer');if(timer)timer.textContent=elapsed(t.dataset.created)})}
    await render();const channel=dq.db.channel(`release2-kds-${rid}-${group}`).on('postgres_changes',{event:'*',schema:'public',table:'kds_tickets',filter:`restaurant_id=eq.${rid}`},schedule).on('postgres_changes',{event:'*',schema:'public',table:'order_items'},schedule).subscribe();function schedule(){clearTimeout(refreshTimer);refreshTimer=setTimeout(render,200)}setInterval(updateTimers,1000);window.addEventListener('beforeunload',()=>dq.db.removeChannel(channel));
  }catch(error){document.getElementById('content').innerHTML=`<div class="empty">${dq.esc(dq.friendlyError(error))}</div>`;dq.err(error)}
})();
