(async function(){
  try{
    const ctx=await dq.requireAuth();if(!ctx)return;const role=dq.roleOf(ctx);if(!['kitchen','bar','owner','manager'].includes(role)){location.replace('dashboard.html');return}
    dq.shell('stations',ctx);const content=document.getElementById('content'),rid=ctx.restaurant.id,group=role==='bar'?'bar':'kitchen';let selected=null;
    const q=async request=>{const {data,error}=await request;if(error)throw error;return data||[]};
    async function render(){const [stations,orders,items,sessions,tables,options]=await Promise.all([q(dq.db.from('prep_stations').select('*').eq('restaurant_id',rid).eq('station_group',group).eq('active',true).order('sort_order')),q(dq.db.from('orders').select('*').eq('restaurant_id',rid).in('status',['pending','accepted','preparing','ready']).order('created_at')),q(dq.db.from('order_items').select('*')),q(dq.db.from('table_sessions').select('id,table_id,assigned_waiter_name').eq('restaurant_id',rid)),q(dq.db.from('physical_tables').select('id,label').eq('restaurant_id',rid)),q(dq.db.from('order_item_modifiers').select('*'))]);if(!selected||!stations.some(s=>s.id===selected))selected=stations[0]?.id||null;const station=stations.find(s=>s.id===selected),tableNames=Object.fromEntries(tables.map(t=>[t.id,t.label])),sessionMap=Object.fromEntries(sessions.map(s=>[s.id,{...s,label:tableNames[s.table_id]||'Table'}])),stationItems=items.filter(item=>item.prep_station_id===selected&&!item.voided_at),orderIds=new Set(stationItems.map(item=>item.order_id)),rows=orders.filter(order=>orderIds.has(order.id));content.innerHTML=`<div class="section-head"><div><span class="eyebrow">Live preparation</span><h1>${group==='bar'?'Bar':'Kitchen'} stations</h1><p>Work one station at a time. Ticket timers continue across every screen.</p></div><span class="live-status"><i></i><span>Live</span></span></div><nav class="station-tabs">${stations.map(s=>`<button class="${s.id===selected?'active':''}" data-station="${s.id}" style="--station:${s.color}"><span></span>${dq.esc(s.name)}<small>${items.filter(i=>i.prep_station_id===s.id&&!i.voided_at&&!['ready','served','rejected'].includes(i.preparation_status)).length}</small></button>`).join('')}</nav>${station?`<div class="kds-board">${rows.map(order=>ticket(order,stationItems.filter(i=>i.order_id===order.id),sessionMap[order.session_id]||{},station,options)).join('')||'<div class="empty">No active tickets at this station.</div>'}</div>`:'<div class="empty">No active preparation stations. Ask an owner or manager to configure menu operations.</div>'}`;bind()}
    function elapsed(value){const mins=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/60000));return mins<60?`${mins}m`:`${Math.floor(mins/60)}h ${mins%60}m`}
    function ticket(order,items,session,station,options){const status=items.some(i=>i.preparation_status==='preparing')?'preparing':items.every(i=>i.preparation_status==='ready')?'ready':order.status==='pending'?'pending':'new',age=Math.floor((Date.now()-new Date(order.created_at).getTime())/60000),timerClass=age>=20?'late':age>=10?'warning':'good';return `<article class="kds-ticket ${status}"><div class="kds-ticket-head" style="--station:${station.color}"><div><span class="route-chip">${dq.esc(station.name)}</span><h2>${dq.esc(session.label||'Table')}</h2><p>Order #${order.order_number} · ${dq.esc(session.assigned_waiter_name||'No waiter assigned')}</p></div><strong class="ticket-timer ${timerClass}">${elapsed(order.created_at)}</strong></div><div class="kds-ticket-items">${items.map(item=>{const mods=options.filter(option=>option.order_item_id===item.id);return `<div><strong>${item.quantity} × ${dq.esc(item.item_name_snapshot)}</strong>${mods.length?`<small>${mods.map(mod=>dq.esc(mod.modifier_name_snapshot)).join(' · ')}</small>`:''}${item.special_instructions?`<em>${dq.esc(item.special_instructions)}</em>`:''}</div>`}).join('')}</div><div class="kds-ticket-actions">${order.status==='pending'?'<span class="muted">Waiting for waiter approval</span>':status==='new'?`<button class="btn station-next" data-order="${order.id}" data-next="preparing">Start preparing</button>`:status==='preparing'?`<button class="btn station-next" data-order="${order.id}" data-next="ready">Mark ready</button>`:'<span class="badge ready">Ready for service</span>'}</div></article>`}
    function bind(){document.querySelectorAll('[data-station]').forEach(button=>button.onclick=()=>{selected=button.dataset.station;render()});document.querySelectorAll('.station-next').forEach(button=>button.onclick=async()=>{dq.setBusy(button,true);try{const {error}=await dq.db.rpc('set_station_order_status_v2',{target_order:button.dataset.order,target_station:selected,next_status:button.dataset.next});if(error)throw error;render()}catch(error){dq.err(error)}finally{dq.setBusy(button,false)}})}
    await render();const channel=dq.db.channel(`station-kds-${rid}`).on('postgres_changes',{event:'*',schema:'public',table:'orders',filter:`restaurant_id=eq.${rid}`},render).on('postgres_changes',{event:'*',schema:'public',table:'order_items'},render).subscribe();window.addEventListener('beforeunload',()=>dq.db.removeChannel(channel));setInterval(()=>{if(!document.hidden)render()},30000);
  }catch(error){document.getElementById('content').innerHTML=`<div class="empty">${dq.esc(dq.friendlyError(error))}</div>`;dq.err(error)}
})();
